name: The Colours
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8432251578196883
title: The Colours Band
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71101e'
    - '#fefaf6'
    - '#ab4f60'
    - '#c89aa5'
    - '#e4d1ce'
  brandStrength: 1
  lightness: 0.7109146760776639
  saturation: 0.4375
  rhythmicContrast: 0.09225680981762707
purpose: []
